# Generated by Django 2.1.2 on 2018-10-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20181024_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('thresholdMax', models.FloatField(blank=True, default=None, null=True)),
                ('thresholdMin', models.FloatField(blank=True, default=None, null=True)),
                ('variable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='measurements.Variable')),
            ],
        ),
    ]
